# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 02:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='file',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
